name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        type: choice
        options:
          - dev
          - preprod
          - prod

jobs:
  branch-check:
    runs-on: self-hosted
    timeout-minutes: 1
    steps:
      - name: Check if running on main branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This workflow can only be run from the main branch"
          echo "Current branch: ${{ github.ref }}"
          echo "Required branch: refs/heads/main"
          exit 1
      
      - name: Confirm main branch
        if: github.ref == 'refs/heads/main'
        run: echo "Running on main branch - proceeding with Terraform workflow"

  terraform-plan:
    needs: branch-check
    runs-on: self-hosted
    timeout-minutes: 15
    outputs:
      env: ${{ steps.set-env.outputs.env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment
        id: set-env
        run: echo "env=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets[format('ROLE_ARN_%s', github.event.inputs.environment)] }}
          aws-region: us-east-1

      - name: Setup Terraform Plugin Cache
        run: |
          mkdir -p ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Select backend for environment
        run: cp terraform/envs/backend_${{ github.event.inputs.environment }}.tf terraform/backend.tf

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan (Generate Plan File)
        working-directory: terraform
        run: terraform plan -var-file="envs/${{ github.event.inputs.environment }}.tfvars" -out=tfplan -input=false -no-color

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan

  approval:
    needs: terraform-plan
    runs-on: self-hosted
    environment:
      name: terraform-approval
    steps:
      - name: Await manual approval
        run: echo "Waiting for manual approval via environment protection"

  terraform-apply:
    needs: approval
    runs-on: self-hosted
    timeout-minutes: 30
    if: ${{ needs.approval.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets[format('ROLE_ARN_%s', github.event.inputs.environment)] }}
          aws-region: us-east-1

      - name: Setup Terraform Plugin Cache
        run: |
          mkdir -p ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Select backend for environment
        run: cp terraform/envs/backend_${{ github.event.inputs.environment }}.tf terraform/backend.tf

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform/

      - name: Terraform Apply (Approved Plan)
        working-directory: terraform
        run: terraform apply tfplan

      - name: Notify on Success
        if: success()
        run: echo "Terraform Apply completed successfully for ${{ github.event.inputs.environment }}"

      - name: Notify on Failure
        if: failure()
        run: echo "Terraform Apply failed for ${{ github.event.inputs.environment }}"