name: Terraform Plan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to plan (dev, preprod, prod)'
        required: true
        type: choice
        options:
          - dev
          - preprod
          - prod

jobs:
  terraform-plan:
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      # Set environment(s): PR detection or manual input
      - name: Set environment
        id: set_env
        shell: bash
        run: |
          EVENT_NAME="${GITHUB_EVENT_NAME:-${{ github.event_name }}}"

          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
            # Manual run
            echo "ENVS=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
            echo "Environment set from manual input: ${{ github.event.inputs.environment }}"
          else
            # PR run: fetch base branch
            git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

            # Detect changed .tfvars files
            CHANGED=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.head_ref }})
            ENVS=$(echo "$CHANGED" | grep '^terraform/envs/.*\.tfvars' | sed 's|terraform/envs/||;s|.tfvars||' | tr '\n' ' ')

            if [ -n "$ENVS" ]; then
              echo "Detected changed environments: $ENVS"
              echo "ENVS=$ENVS" >> $GITHUB_ENV
            elif echo "$CHANGED" | grep -q '^terraform/.*\.tf$'; then
              echo "Core Terraform files changed, planning all environments"
              echo "ENVS=all" >> $GITHUB_ENV
            else
              echo "No relevant environment detected. Exiting workflow."
              exit 1
            fi

      # Configure AWS credentials
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets[format('ROLE_ARN_%s', env.ENVS)] }}
          aws-region: us-east-1

      # Terraform Init & Plan
      - name: Terraform Init & Plan
        working-directory: terraform
        shell: bash
        run: |
          rm -rf .terraform
          terraform init

          if [ "$ENVS" = "all" ]; then
            for E in dev preprod prod; do
              echo "==> Planning environment: $E"
              cp terraform/envs/backend_${E}.tf terraform/backend.tf
              terraform plan -var-file="envs/${E}.tfvars" -input=false -no-color | tee "plan_${E}.txt"
            done
          else
            for E in $ENVS; do
              echo "==> Planning environment: $E"
              cp terraform/envs/backend_${E}.tf terraform/backend.tf
              terraform plan -var-file="envs/${E}.tfvars" -input=false -no-color | tee "plan_${E}.txt"
            done
          fi

      # Post plan as PR comment (PR only)
      - name: Comment Terraform Plan on PR
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          if [ "$ENVS" = "all" ]; then
            for E in dev preprod prod; do
              PLAN=$(cat terraform/plan_${E}.txt)
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d "{\"body\": \"**Terraform Plan for ${E}**\n\`\`\`terraform\n$PLAN\`\`\`\"}" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
            done
          else
            for E in $ENVS; do
              PLAN=$(cat terraform/plan_${E}.txt)
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d "{\"body\": \"**Terraform Plan for ${E}**\n\`\`\`terraform\n$PLAN\`\`\`\"}" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
            done
          fi

      # Notify success/failure
      - name: Notify on Success
        if: success()
        run: echo "Terraform Plan completed successfully for ${{ env.ENVS }}"

      - name: Notify on Failure
        if: failure()
        run: echo "Terraform Plan failed for ${{ env.ENVS }}"
